resolver: lts-12.4

packages:
  - '.'

# GHC heap view will fail to build
extra-deps:
  - git: https://github.com/patrickdoc/hash-graph.git
    commit: 785c20dc608774b133d89c942bc33d7f56ef6ced
  - git: https://github.com/snowleopard/alga.git
    commit: 4d8a403a6d0de083c3fb7a3dc8e2267f02cfde15
  - Chart-1.9
  - Chart-cairo-1.9
  - criterion-1.5.1.0
  - criterion-measurement-0.1.1.0

# So we disable it
flags:
  bench-graph:
    datasize: false
