resolver: lts-13.27

packages:
  - '.'

# GHC heap view will fail to build
extra-deps:
  - git: https://github.com/patrickdoc/hash-graph.git
    commit: 785c20dc608774b133d89c942bc33d7f56ef6ced
  - git: https://github.com/snowleopard/alga.git
    commit: 35465faff04f0f2a608c5761f62cc65dee122b71

# So we disable it
flags:
  bench-graph:
    datasize: false
